# Generated by Django 4.2.4 on 2023-09-15 15:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('watercan_supply_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_ordered', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.IntegerField(default=1)),
                ('is_completed', models.BooleanField(default=True)),
                ('watercan_info', models.ManyToManyField(to='watercan_supply_management.watercan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(default=1)),
                ('date_paid', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='watercan_supply_management.userinfo')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order_management.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
