# Generated by Django 4.2.9 on 2024-01-12 06:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("QuickInvoice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="invoicedetail",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
